### ISSUE TITLE
[Quilt] Crash on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [Nova-Committee/More-Leads#1]
**MC** 1.19.2
**QSL** 4.0.0 beta 10
**MoreLeads** 1.0.0

Fabric version works, only the Quilt one is causing issues.

Logs: https://gist.github.com/SplendidAlakey/c397d215c0d76bea900bef16a12370a2

**Comment by VulpesStella** [comment]
[This line](https://github.com/Nova-Committee/More-Leads/blob/67737e8cb1ce36d7b282682433570e91b9c0e81b/src/main/resources/quilt.mod.json#L20) seems to miss the class name, will try to fix it.

**Comment by SplendidAlakey** [comment]
Just tested version 1.0.1 and the issue still occurs, updated logs: https://gist.github.com/Footage2-Amply-Pounce/c397d215c0d76bea900bef16a12370a2

**Comment by VulpesStella** [comment]
Was there any change in Quilt itself?

**Comment by SplendidAlakey** [comment]
I updated from 0.17.4 to 0.17.5-beta.2, so I assume yes: https://github.com/QuiltMC/quilt-loader/commits/develop

However, I just tested it on a fresh 0.17.4 install and the crash is still present there, the crash logs are identical to the one produced with 0.17.5-beta.2.

**Comment by VulpesStella** [comment]
We were using fabric's intermediary mappings, which may be the issue😂.
I'll soon give it a check.
